### ISSUE TITLE
Cron?

### ISSUE THREAD

**Issue by badger28** [ccrisan/motionPie#96] opened 2015-02-03 18:47 UTC
Cron doesn't seem to be present...
Is there anyway I can use cron within motionpie to update a dynamic ip address?

This would allow me to view the stream while I am away from home.  Or is there an easier way of me achieving this?

Thanks

**Comment by ccrisan** [comment] 2015-02-03 19:40
No, there's no such option, for now.

**Comment by ccrisan** [comment] 2015-03-31 19:44
Duplicate of https://github.com/ccrisan/motionPie/issues/127

**Closed by ccrisan** 2015-03-31 19:44 UTC
