### ISSUE TITLE
Capturing Sound

### ISSUE THREAD

**Issue by NathTheDude** [ccrisan/motionpie#222] opened 2015-06-18 07:40 UTC
Hi there,

I apologise if this is not in the correct area but I am new to github. I have been looking for a sutible application/build for a home petcam although going towards a full house survellence system for some time whilst only using a Raspberry pi and a cam (RPI cam or USB). Although there are few options I do struggle with customising it as my linux knowledge is basic and troubleshooting can take a long time.

Your project looks awesome and seems like it would be perfect for what I need it for, I am going to do some test installs at the weekend but thought I would ask of the possibility of using this with sound?

Many thanks.

**Comment by ccrisan** [comment] 2015-06-18 10:19
Duplicate of https://github.com/ccrisan/motionpie/issues/63.

**Closed by ccrisan** 2015-06-18 10:19 UTC
Labels: duplicate
