### ISSUE TITLE
Enable motion detection for part of the frame only

### ISSUE THREAD

**Issue by SuperSharpShooter** [ccrisan/motionpie#64] opened 2015-01-11 03:17 UTC
Is there a way to add an option to only enable motion detection for a certain part of the frame?

I'm getting way too many false positives on my camera, as there are trees which sway in the wind at the top of the frame (which sets the camera off), but I am only interested in motion in the lower half of the frame where the driveway is. 

Just using the current sensitivity settings, it's impossible to stop the false positives, while allowing the camera to still be triggered reliably when there is a car or person in the lower frame.

Even if there was a square box of various sizes or positions in which motion would be detected, then the false positives could be cut down drastically.

**Comment by ccrisan** [comment] 2015-01-11 09:02
This is the feature you're looking for: https://bitbucket.org/ccrisan/motioneye/issue/68/image-mask-feature-request. It's going to happen some time in the future.

**Comment by SuperSharpShooter** [comment] 2015-01-11 09:03
Alright, thanks for that. Look forward to it being implemented.

**Comment by ccrisan** [comment] 2015-05-16 20:36
Duplicate of https://github.com/ccrisan/motionpie/issues/64.

**Closed by ccrisan** 2015-05-16 20:36 UTC
Labels: duplicate
