### ISSUE TITLE
Unable to run motionPie with the Pi camera on an RPi model A+

### ISSUE THREAD

**Issue by gitgoldberg** [ccrisan/motionpie#30] opened 2014-11-22 08:50 UTC
Congratulations on an excellent application.

I'm using the latest motionPie-20140928.img release.

It was very easy to set up and use on an RPI model B+.

What I then hoped to be able to do was transfer the microSD card created on the B+, Pi CSI camera, and Edimax EW7811Un dongle to the RPi model A+

Everything boots up OK, and the web page is accessible, but the following messages indicate that the Pi CSI camera is not set up correctly:
You have not configured any camera yet.  Click here to add one...
An error occurred. Refreshing is recommended.

When I try to run 'Add Camera', the only options offered are 'Network camera' and 'Remote motionEye camera' - there is no option for the Pi CSI camera.

On SSH'ing in as root, it appears that the /dev/video0 device is not being created during initialisation, see attached /data/log/motioneye.log

The model A+ is running on a 2 amp power supply, and when run from a microSD containing the latest 2014-09-09  Raspbian Debian Wheezy image, is able to capture still images using the raspistill command. So the Pi camera and the model A+'s CSI port are known to be OK.

When the SD card, Edimax, and Pi camera are moved back to the model B+  motionPie works fine again and the Pi CSI camera is recognised and usable again.

Is it possible that that the 256Mb RAM on the A+ as opposed to 512Mb on the B+ is somehow preventing the /dev/video0 device from being created ?

![motioneye log 2014-11-22 at 22 14 04](https://cloud.githubusercontent.com/assets/6689015/5155895/bcc6d130-7295-11e4-97c2-ebe788ebe303.png)

**Comment by dewnut** [comment] 2015-03-28 15:48
Hi - I am having this issue with the Raspberry Pi 2.  I am running motionpie-raspberrypi2-20150317 with the OV5647 camera.  Thanks!

**Comment by dkelley810** [comment] 2015-03-28 16:20
I believe for the A + you should have used motionpie-raspberrypi-20150317

You used the one for raspberry pi 2
Let us know if that works.

Dennis Kelley

**Comment by dewnut** [comment] 2015-03-28 17:00
Thanks, no I have a RP2

**Comment by dewnut** [comment] 2015-03-30 17:32
I'd be happy to test my cam with a new release for you...

**Comment by ccrisan** [comment] 2015-03-30 18:58
It's coming soon but I still need to test some new features.

**Comment by dewnut** [comment] 2015-03-30 21:56
I understand.  Could you tell me how to ssh into the motionpie build so I could try finding and installing drivers myself perhaps?  Also, motionpie is the only way I've been able to get my wifi dongle working too, I'd like to look at your configuration for that!

Thanks!

**Comment by ccrisan** [comment] 2015-03-31 06:50
Read [this](https://github.com/ccrisan/motionPie/wiki/Troubleshooting#shell-access) and [this](https://github.com/ccrisan/motionPie/wiki/FAQ#shell-access) to learn how to access the shell.

And there's nothing special about the wifi configuration. The kernel config is the same as the one that comes with Raspbian and the /data/etc/wpa_supplicant.conf file is fairly simple.

**Comment by atux** [comment] 2015-04-04 11:04
i am running an rpi b with raspbian. all updated/upgraded to latest. i am having issues installing motioneye. it comes with this error:
root@raspberrypi:/home/pi/motioneye# ./motioneye.py
please install tornado (python-tornado), version 3.1 or greater
root@raspberrypi:/home/pi/motioneye#

**Comment by ccrisan** [comment] 2015-04-04 11:05
If you use Raspbian, then this is not the place to report your problems. See [this](https://bitbucket.org/ccrisan/motioneye/issue/135/motioneye-not-running-after-024-upgrade) to fix your tornado version issue.

**Comment by jimmyeao** [comment] 2015-04-19 18:17
just set this up on a B and it isn't detecting the Pi Camera?

**Comment by ccrisan** [comment] 2015-04-19 19:37
modprobe bcm2835-v4l2?

**Comment by jimmyeao** [comment] 2015-04-19 20:07
modprobe: can't load module bcm2835-v4l2 (kernel/drivers/media/platform/bcm2835/                                                                                                                        bcm2835-v4l2.ko): Operation not permitted

**Comment by ccrisan** [comment] 2015-04-19 20:41
sudo modprobe bcm2835-v4l2?

**Comment by jimmyeao** [comment] 2015-04-19 21:11
i'm in as root already,.. camera was working on my Pi2 before i moved it to my model b, ill remove and re-install tomorrow.
The camera light flicks on and off on boot up if that means anything?

**Comment by jimmyeao** [comment] 2015-04-19 21:12
if i run dmesg i get 
[ 5616.852823] : bcm2835-v4l2: error -1 while loading driver
[ 5643.389059] : bcm2835-v4l2: error -1 while loading driver

**Comment by ccrisan** [comment] 2015-04-19 21:15
That looks like a camera/hw fault. If you disconnect the ribbon you get such an error message when trying to load the module.

Please take this to the raspberry pi forums as the issue is not related to motionPie.

**Comment by wientanz** [comment] 2015-05-08 22:12
I have exactly the same problem as jummyeao (also on a RPi B+)... I tried two Pi cameras, one that I previously had installed on a RPi 2 under Raspian, where it was working perfectly. I even tried modprobe and dmesg with exactly the same results. So I think I can exclude an HW damage. I even rewrote the SD card with the motionpie image again. Still nothing.

**Comment by ccrisan** [comment] 2015-05-11 09:51
@wientanz can you please try to install Raspbian and see if it works fine on Raspbian? By working fine I mean the raspistill command, for example, captures a frame successfully.

**Comment by wientanz** [comment] 2015-05-11 10:31
Hi, thank your for my reply. Please disregard my topic as I figured out my issue... I managed to connect the Camera to the wrong connection. So, yes, it was an HW issue after all. And the problem sat behind the keyboard. *blush* (and that after I managed to properly connect it on the RPi2 I tried it out on a few weeks ago)

**Comment by jimmyeao** [comment] 2015-05-11 13:43
Mine was down to an incorrectly seated ribbon cable also, just in case anyone else gets here. @ccrisan is usually right in his observations ;)

**Comment by mikecarr** [comment] 2015-06-22 03:58
Just tried motionpie-raspberrypi-20150601 (several times), at first everything is going ok. After a few updates, around wireless config, I see "An error occurred. Refreshing is recommended." After that I can no longer get an IP or connect.

**Comment by ccrisan** [comment] 2015-06-22 07:07
Could you please send me the logs? (see [here](https://github.com/ccrisan/motionpie/wiki/Reporting-An-Issue#attach-log-files) how to do that)

**Comment by mikecarr** [comment] 2015-06-22 16:35
Here you go http://s000.tinyupload.com/index.php?file_id=43279880103507656048
I cannot log into the console so I mounted the sdcard on my mac and copied the log files. I have also tried several different sdcards with the same result.

**Comment by ccrisan** [comment] 2015-06-23 10:03
@mikecarr:
1. Is this a fresh install or an upgrade?
2. What camera do you have installed? Was it detected automatically or did you have to add it manually?
3. What precise settings did you change in the settings panel when the problem occurred?
4. Is your problem fully reproducible (i.e. can you reproduce it from scratch each time)?

**Comment by mikecarr** [comment] 2015-06-24 17:57
1. Is this a fresh install or an upgrade? *Fresh*
2. What camera do you have installed? Was it detected automatically or did
you have to add it manually? *I am using pi camera and it was detected*
3. What precise settings did you change in the settings panel when the
problem occurred?
*It seems to occur every time I adjust network settings*
4. Is your problem fully reproducible (i.e. can you reproduce it from
scratch each time)?
*Yes*

**Comment by ccrisan** [comment] 2015-07-12 20:08
@mikecarr apologies for getting back to you with such a delay. Could you also please send me the /data/etc/motioneye.conf file? You could simply paste its contents here.

**Comment by mikecarr** [comment] 2015-07-12 23:21
Here you go, no worries.

**Comment by ccrisan** [comment] 2015-07-13 06:34
I'm sorry but I cannot seem to find the link to the file, or its contents.

**Comment by ccrisan** [comment] 2015-07-14 18:36
@mikecarr I'm still waiting for your /data/etc/motioneye.conf.

Also, I cannot seem to reproduce your problem. You said it was fully reproducible and that you managed to reproduce it several times. Could you please tell me the exact steps that you follow to reproduce the problem, from the moment you write the image on the SD card?

Moreover, you said that the error appears when changing the wireless network settings. If you're on a Raspberry PI model A, you couldn't possibly change those settings so that the connection works before as well as after changing it, could you?

**Comment by mikecarr** [comment] 2015-07-14 18:54
It was in the last response, maybe attachments don't go through?

https://www.dropbox.com/s/wvv8wclyq6rbrv5/motioneye.conf?dl=0

**Comment by ccrisan** [comment] 2015-07-14 19:04
If you replied to the automated github mail, the attachment was removed by github. Anyways, I would really need you to walk me through the entire process. What exactly do you do to get the system into this state. Your motioneye,conf file contains three entries for "motion-binary", all of them being empty, which is really odd.

**Comment by mikecarr** [comment] 2015-07-14 21:32
I setup everything as normal, the first time it starts I can view the
camera. As soon as I try to configure anything, usually the Wireless
settings, I get the error. I will video my steps and post on YouTube when I
get time.

**Comment by ccrisan** [comment] 2015-07-15 06:36
That would be great. Thanks.

**Comment by mikecarr** [comment] 2015-07-22 19:20
Dang, happened again with the latest version. This time I had wireless
setup, but was enabling video. When I selected Apply, it gave the reboot
warning message after apply, then I get the error that says I need to
reload. I then reflashed the SD Card, did the same setup and it worked this
time, probably because I was recording the second time it worked. I have
all the logs for the failed one. Could the camera be taking too long to
start up giving a null value?


​
Could there me a default value that is null?

2015-07-22 18:13:38: ERROR: invalid literal for int() with base 10: 'null'
Traceback (most recent call last):
  File
"home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/web.py",
line 1302, in _stack_context_handle_exception
  File
"home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/web.py",
line 1489, in wrapper
  File "/programs/motioneye/src/handlers.py", line 188, in post
    self.set_config(camera_id)
  File "/programs/motioneye/src/handlers.py", line 121, in wrapper
    return func(self, *args, **kwargs)
  File "/programs/motioneye/src/handlers.py", line 414, in set_config
    set_camera_config(int(key), cfg, check_finished)
ValueError: invalid literal for int() with base 10: 'null'
2015-07-22 18:13:38: ERROR: 500 POST
/config/0/set/?_=1437588818623&_username=admin&_signature=fd6f72d09258159e2497b42fffb21d5390d383c1
(192.168.43.72) 652.92ms
2015-07-22 18:13:57: ERROR: authentication failed for user admin
2015-07-22 18:14:04: ERROR: authentication failed for user admin
2015-07-22 18:14:20: ERROR: authentication failed for user admin
2015-07-22 18:14:35: ERROR: authentication failed for user admin
2015-07-22 18:14:42: ERROR: authentication failed for user admin

**Comment by ccrisan** [comment] 2015-07-22 20:13
It's hard to tell. I never managed to reproduce the problem and I was really looking forward to your video with instructions. Could you please take a few minutes of your spare time and try reproducing it with the older version?

**Comment by mikecarr** [comment] 2015-07-22 20:27
Sure, it happened again just at a different moment. I will try again.

**Comment by mikecarr** [comment] 2015-07-23 01:14
Unreal, I am now unable to reproduce it.

**Comment by mikecarr** [comment] 2015-07-23 01:23
Got it! On the newer version.

**Comment by mikecarr** [comment] 2015-07-23 01:28
http://screencast.com/t/jXDKjnUZOx

**Comment by ccrisan** [comment] 2015-07-23 06:27
Thanks! I'll try to reproduce it step by step. This is an A+ with a freshly installed 20150719, right? If it's an A+, how do you connect to it before configuring the WiFi?

**Comment by mikecarr** [comment] 2015-07-23 16:27
The one I have looks like this
https://upload.wikimedia.org/wikipedia/commons/3/3d/RaspberryPi.jpg. I am
going to do some testing and see if the issue is specific to my router
(Airport Extreme). The issue also occurred when hard wired. It looks like I
get that message ...'an error occurred, a refresh may help' (something like
that). If I refresh the browser I can no longer login or connect to it.
wpa_supplicant reverts back, really odd.

**Comment by mikecarr** [comment] 2015-07-23 16:33
In addition this happened hardwired with a Raspberry Pi 2 with the latest
firmware. I am just not having any luck with this.

**Comment by ccrisan** [comment] 2015-07-23 20:29
Well your PI is a model B rev 1.0, not a model A, so this is probably the wrong place to discuss the problem. Nevertheless, the issue is a valid issue and shouldn't be model-dependent. I'll look into it this weekend and will keep you posted. Again, thanks for taking the time to put all the required details together.

**Comment by mikecarr** [comment] 2015-07-24 18:09
Is there a way I can check the credentials? I am trying to pinpoint why the
credentials no longer work, this may lead me to find out what is going on.

**Comment by mikecarr** [comment] 2015-07-24 19:37
Quick update, I switched sd cards and I have not had an issue yet. I was
using a SanDisk Ultra HCI class 10 in the Raspberry Pi2. Will continue to
test.

-Mike

**Comment by mikecarr** [comment] 2015-07-24 20:32
I am wondering if corruption occurs because the app could be detecting
motion and writing to the SD card, then when a change is made in the GUI,
the config never gets written or if the unit reboots during a write if that
causes corruption on the sd card. Maybe an option is to disable motion
detection when user hits apply or when a user is in the configuration
window, wait for some time (configurable) to allow writing to complete,
then reboot.

I will test out this theory by disabling all motion sensing with the other
card and play with UI.

Just some ideas.

**Comment by mikecarr** [comment] 2015-07-24 20:37
Scratch that, it just crapped out again.

**Comment by ccrisan** [comment] 2015-07-24 20:41
Thanks for trying to find the root cause of the problem. I haven't had too much time these days but I'll do my best to reproduce and find the problem myself this weekend.

One more thing, If you manage to reproduce the problem just like you did when you recorded that screencast, could you please also save *all* the log files, so I can correlate what I see in the screencast with that various parts of the system say in their log files?

**Comment by mikecarr** [comment] 2015-07-24 20:47
Sure, what I have noticed is that it looks it reverts to default values. On
a reboot it sets the password back to serial number, motion.conf loses all
the information that was previously set. I was tailing both motion.log and
motioneye.log and I did not see anything out of the ordinary, really odd.
It seems as though /data gets corrupt or reverts?

**Comment by ccrisan** [comment] 2015-07-26 09:07
After trying numerous times to reproduce your problem without any success, I saw that, at moment 1:22 - 1:24 (in your screencast), the apply button appears out-of-the-blue without having anything modified in the settings panel. That's definitely not normal and that's probably what makes the UI send messed-up config data to the server.

I'm going to ask you to dedicate another few minutes of your time to recreate the scenario (from scratch), in order to debug the problem. Here are some ideas:

1) try clicking all the OK buttons when logging in (i.e. do not hit enter)  and see if the problem persists
2) try setting simple passwords for `admin`  and `mcarr` (i.e. no special characters)
3) try another browser and see if the problem persists (there might be some problematic chrome extensions)
4) if the problem is still there, would you be comfortable to set up a remote debugging session over teamviewer, vnc, remote desktop or whatever you like?

**Comment by mikecarr** [comment] 2015-07-27 18:32
1) I always clicked on the OK buttons, probably could not see this in the
video
2) I was using simple passwords
3) I am using Safari (on Mac) now and so far it works a lot better, no
crashes yet and no weird behavior. If this continues to work I will go back
to Chrome and try Incognito mode.
4) if this continues to be a problem we could setup a remote debugging

-Mike

**Comment by mikecarr** [comment] 2015-07-28 04:02
I have been using it all day and no issues, will continue tomorrow.

**Comment by ccrisan** [comment] 2015-07-28 10:33
Do you have some chrome extensions installed and active? Technically speaking, the problem manifests as though the javascript state was preserved by the browser across refreshes. And I'm not talking about caching, but rather about the entire state of the page (variables and whatnot).

Now, given that when using motionEye, the location entry never changes (the UI is a simple, single-page UI), something about your browser might consider that preserving the state across refreshes could be safe.

**Comment by mikecarr** [comment] 2015-07-28 16:40
It is definitely something with Chrome, I had been using Safari and no
issues at all. I tried Chrome and the first time I loaded the page I
noticed the Apply button available, as soon as I clicked on it I saw the
familiar message and poof..corrupt. I am going to disable all plugins and
extensions and load them one by one.

**Comment by mikecarr** [comment] 2015-07-28 20:36
I think I have the issue narrowed down to the 1Password extension, as soon
as I enable that I get the error.

Here is the request payload that is sent to the server

{
   "1":{
      "enabled":true,
      "name":"Camera1",
      "proto":"v4l2",
      "light_switch_detect":true,
      "auto_brightness":false,
      "rotation":"0",
      "framerate":"2",
      "extra_options":[

      ],
      "storage_device":"custom-path",
      "network_server":"",
      "network_share_name":"",
      "network_username":"",
      "network_password":"",
      "root_directory":"/data/output",
      "text_overlay":true,
      "left_text":"camera-name",
      "custom_left_text":"",
      "right_text":"timestamp",
      "custom_right_text":"",
      "video_streaming":true,
      "streaming_framerate":"5",
      "streaming_quality":"85",
      "streaming_resolution":"100",
      "streaming_server_resize":false,
      "streaming_port":"8081",
      "streaming_auth_mode":"disabled",
      "streaming_motion":false,
      "still_images":true,
      "image_file_name":"%Y-%m-%d/%H-%M-%S",
      "image_quality":"85",
      "capture_mode":"motion-triggered",
      "snapshot_interval":"0",
      "preserve_pictures":"30",
      "motion_detection":true,
      "show_frame_changes":false,
      "frame_change_threshold":"2.6028645833333335",
      "auto_noise_detect":true,
      "noise_level":"12",
      "event_gap":"10",
      "pre_capture":"2",
      "post_capture":"4",
      "minimum_motion_frames":"1",
      "motion_movies":true,
      "movie_file_name":"%Y-%m-%d/%H-%M-%S",
      "movie_quality":"86",
      "max_movie_length":"0",
      "preserve_movies":"30",
      "email_notifications_enabled":false,
      "email_notifications_addresses":"",
      "email_notifications_smtp_server":"",
      "email_notifications_smtp_port":"",
      "email_notifications_smtp_account":"",
      "email_notifications_smtp_password":"",
      "email_notifications_smtp_tls":false,
      "email_notifications_picture_time_span":"",
      "web_hook_notifications_enabled":false,
      "web_hook_notifications_url":"",
      "web_hook_notifications_http_method":"GET",
      "command_notifications_enabled":false,
      "command_notifications_exec":"",
      "working_schedule":true,
      "monday_from":"01:00",
      "monday_to":"07:30",
      "tuesday_from":"02:00",
      "tuesday_to":"02:30",
      "wednesday_from":"01:00",
      "wednesday_to":"22:00",
      "thursday_from":"08:00",
      "thursday_to":"15:00",
      "friday_from":"01:00",
      "friday_to":"02:00",
      "saturday_from":"01:00",
      "saturday_to":"08:00",
      "sunday_from":"",
      "sunday_to":"",
      "working_schedule_type":"outside",
      "resolution":"320x240",
      "brightness":"50",
      "contrast":"50",
      "saturation":"50"
   },
   "main":{
      "enabled":false,
      "show_advanced":false,
      "admin_username":"",
      "admin_password":"",
      "normal_username":"",
      "normal_password":"",
      "_timeZone":"Africa/Abidjan",
      "_wifiEnabled":false,
      "_wifiNetworkName":"",
      "_wifiNetworkKey":"",
      "_ipConfigType":"dhcp",
      "_ipConfigStaticAddr":"",
      "_ipConfigStaticMask":"",
      "_ipConfigStaticGw":"",
      "_ipConfigStaticDns":"",
      "_ftpEnabled":false,
      "_ftpAuth":false,
      "_ftpWritable":false,
      "_smbEnabled":false,
      "_smbAuth":false,
      "_smbWritable":false,
      "_sshEnabled":false,
      "_watchLink":false,
      "_watchLinkTimeout":0,
      "_watchConnect":false,
      "_watchConnectHost":"",
      "_watchConnectPort":0,
      "_watchConnectRetries":0,
      "_watchConnectTimeout":0,
      "_watchConnectInterval":0,
      "_dateMethod":"http",
      "_dateHost":"",
      "_dateTimeout":0,
      "_dateInterval":0,
      "_port":0,
      "_motionBinary":"",
      "_motionKeepAlive":false,
      "_debug":false,
      "_prereleases":false,
      "_streamEye":false,
      "_gpuMem":0,
      "_cameraLed":false,
      "_overclock":"700|250|400|0"
   },
   "null":{
      "enabled":false,
      "name":"",
      "light_switch_detect":false,
      "auto_brightness":false,
      "rotation":"0",
      "framerate":"",
      "extra_options":[

      ],
      "storage_device":null,
      "network_server":"",
      "network_share_name":"",
      "network_username":"",
      "network_password":"",
      "root_directory":"",
      "text_overlay":false,
      "left_text":"camera-name",
      "custom_left_text":"",
      "right_text":"camera-name",
      "custom_right_text":"",
      "video_streaming":false,
      "streaming_framerate":"",
      "streaming_quality":"",
      "streaming_resolution":"",
      "streaming_server_resize":false,
      "streaming_port":"",
      "streaming_auth_mode":"disabled",
      "streaming_motion":false,
      "still_images":false,
      "image_file_name":"",
      "image_quality":"",
      "capture_mode":"motion-triggered",
      "snapshot_interval":"",
      "preserve_pictures":"1",
      "motion_detection":false,
      "show_frame_changes":false,
      "frame_change_threshold":"",
      "auto_noise_detect":false,
      "noise_level":"",
      "event_gap":"",
      "pre_capture":"",
      "post_capture":"",
      "minimum_motion_frames":"",
      "motion_movies":false,
      "movie_file_name":"",
      "movie_quality":"",
      "max_movie_length":"",
      "preserve_movies":"1",
      "email_notifications_enabled":false,
      "email_notifications_addresses":"",
      "email_notifications_smtp_server":"",
      "email_notifications_smtp_port":"",
      "email_notifications_smtp_account":"",
      "email_notifications_smtp_password":"",
      "email_notifications_smtp_tls":false,
      "email_notifications_picture_time_span":"",
      "web_hook_notifications_enabled":false,
      "web_hook_notifications_url":"",
      "web_hook_notifications_http_method":"GET",
      "command_notifications_enabled":false,
      "command_notifications_exec":"",
      "working_schedule":false,
      "monday_from":"",
      "monday_to":"",
      "tuesday_from":"",
      "tuesday_to":"",
      "wednesday_from":"",
      "wednesday_to":"",
      "thursday_from":"",
      "thursday_to":"",
      "friday_from":"",
      "friday_to":"",
      "saturday_from":"",
      "saturday_to":"",
      "sunday_from":"",
      "sunday_to":"",
      "working_schedule_type":"during"
   }
}

**Comment by ccrisan** [comment] 2015-07-28 20:58
Well the `"null"` dictionary key certainly doesn't look good. Anyways, thanks for taking the time to identify the root cause of this problem. Although the issue title doesn't really express this particular problem, I'm glad you managed to sort it out here. I'll close the issue now.

**Closed by ccrisan** 2015-07-28 20:58 UTC
